config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    resources :restaurants, only: [:new, :create, :index, :show] do
      resources :reviews, only: [:new, :create]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :category, inclusion: { in: CATEGORIES }
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: {in: (0..5).to_a}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: unprocessible_entity
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])

  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessible_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%#= f.input :species, collection: Pet::SPECIES %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container mt-3">
    <h1>Restaurants</h1>
  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant) do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= restaurant.name %>
  </div>
      <% end %>
    <% end %>
</div>
</div>

app/views/restaurants/new.html.erb
<%= render "form" %>

app/views/restaurants/show.html.erb
<div class="container mt-3">
  <h1><%= @restaurant.name %></h1>
  <div class="cards p-3 bg-light">
  <ul>
  <%= @restaurant.address %></p>
  <%= @restaurant.phone_number %></p>
  <%= @restaurant.category %></p>
  </ul>
  </div>
       <h4>
        <%= link_to "Back to List", restaurants_path %>
        <%# <%= link_to "Edit this task", edit_path %>
        <%= link_to new_restaurant_review_path(@restaurant), class: "btn btn-primary" do %>
        <i class="fa-solid fa-plus"></i> <span>Add review</span>
        <% end %>
        </h4>

        <ul>
        <% @restaurant.reviews.each do |review| %>
        <li>
        <%= review.content %>
        <%= review.rating %>
        </li>
        <% end %>
        </ul>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, input_html: { min: 0, max: 5 } %>
  <%#= f.input :species, collection: Pet::SPECIES %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form" %>